In [1]:
import numpy as np

In [2]:
A1 = np.random.rand(5, 5)
A1

array([[0.90447607, 0.87609596, 0.82625153, 0.27734692, 0.77049176],
       [0.25648661, 0.04452698, 0.5926634 , 0.85179692, 0.648986  ],
       [0.88881007, 0.98300707, 0.82306694, 0.65342329, 0.62462184],
       [0.76214961, 0.54638382, 0.43604101, 0.86313681, 0.16898734],
       [0.11730188, 0.85744745, 0.50330653, 0.58469897, 0.87784551]])

In [33]:
print(np.linalg.matrix_rank(A1))
print(np.linalg.det(A1))
print(np.linalg.eig(A1))


5
-0.05556823190238583
(array([ 3.1339375 +0.j        , -0.58361738+0.j        ,
        0.44417562+0.45952696j,  0.44417562-0.45952696j,
        0.07438094+0.j        ]), array([[-0.52150995+0.j        ,  0.13848178+0.j        ,
        -0.09293025-0.52563414j, -0.09293025+0.52563414j,
         0.37740366+0.j        ],
       [-0.33912651+0.j        , -0.8674805 +0.j        ,
         0.07091655+0.20250134j,  0.07091655-0.20250134j,
        -0.10313354+0.j        ],
       [-0.55919888+0.j        ,  0.31036308+0.j        ,
        -0.15356588-0.09320304j, -0.15356588+0.09320304j,
        -0.7594389 +0.j        ],
       [-0.39247294+0.j        ,  0.12111545+0.j        ,
        -0.39452383+0.356392j  , -0.39452383-0.356392j  ,
         0.01528848+0.j        ],
       [-0.38246855+0.j        ,  0.34249992+0.j        ,
         0.59506569+0.j        ,  0.59506569-0.j        ,
         0.51956594+0.j        ]]))


In [20]:
T = A1.T
T

array([[0.90447607, 0.25648661, 0.88881007, 0.76214961, 0.11730188],
       [0.87609596, 0.04452698, 0.98300707, 0.54638382, 0.85744745],
       [0.82625153, 0.5926634 , 0.82306694, 0.43604101, 0.50330653],
       [0.27734692, 0.85179692, 0.65342329, 0.86313681, 0.58469897],
       [0.77049176, 0.648986  , 0.62462184, 0.16898734, 0.87784551]])

In [34]:
print(np.linalg.matrix_rank(T))
print(np.linalg.det(T))
print(np.linalg.eig(T))

5
-0.05556823190238578
(array([ 3.1339375 +0.j        , -0.58361738+0.j        ,
        0.44417562+0.45952696j,  0.44417562-0.45952696j,
        0.07438094+0.j        ]), array([[-0.41578408+0.j        ,  0.17840842+0.j        ,
         0.19113747+0.50563466j,  0.19113747-0.50563466j,
         0.41113236+0.j        ],
       [-0.46483474+0.j        ,  0.84548284+0.j        ,
         0.04649179-0.13188189j,  0.04649179+0.13188189j,
        -0.07863941+0.j        ],
       [-0.45085618+0.j        , -0.25581137+0.j        ,
         0.15957971-0.06124037j,  0.15957971+0.06124037j,
        -0.76977577+0.j        ],
       [-0.46701896+0.j        , -0.28417095+0.j        ,
        -0.6409028 +0.j        , -0.6409028 -0.j        ,
         0.44974171+0.j        ],
       [-0.43551609+0.j        , -0.3273173 +0.j        ,
         0.12250294-0.4829765j ,  0.12250294+0.4829765j ,
         0.17310022+0.j        ]]))


При транспонировании ранг, определитель и собственные значения матрицы не меняются.

In [23]:
A1I = np.linalg.inv(A1)
A1I

array([[ 3.4963486 , -0.43707734, -4.76230318,  2.84910331,  0.09446481],
       [-1.2432708 , -1.05760228,  1.79857982, -0.36835931,  0.66425674],
       [-4.70890824,  1.44429271,  9.13553181, -5.17621554, -2.438571  ],
       [-0.68568266,  0.31535617, -0.34924356,  1.05103516,  0.41486186],
       [ 3.90370888,  0.05331005, -6.12560061,  2.24678197,  1.59952205]])

In [35]:
print(np.linalg.matrix_rank(A1I))
print(np.linalg.det(A1I))
print(np.linalg.eig(A1I))

5
-17.995893800555915
(array([13.44430394+0.j        , -1.71345136+0.j        ,
        1.08744768+1.12503139j,  1.08744768-1.12503139j,
        0.31908741+0.j        ]), array([[ 0.37740366+0.j        , -0.13848178+0.j        ,
        -0.09293025+0.52563414j, -0.09293025-0.52563414j,
         0.52150995+0.j        ],
       [-0.10313354+0.j        ,  0.8674805 +0.j        ,
         0.07091655-0.20250134j,  0.07091655+0.20250134j,
         0.33912651+0.j        ],
       [-0.7594389 +0.j        , -0.31036308+0.j        ,
        -0.15356588+0.09320304j, -0.15356588-0.09320304j,
         0.55919888+0.j        ],
       [ 0.01528848+0.j        , -0.12111545+0.j        ,
        -0.39452383-0.356392j  , -0.39452383+0.356392j  ,
         0.39247294+0.j        ],
       [ 0.51956594+0.j        , -0.34249992+0.j        ,
         0.59506569+0.j        ,  0.59506569-0.j        ,
         0.38246855+0.j        ]]))


Обратная матрица имеет тот же ранг, что и исходная.

In [16]:
I = np.eye(4, 4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
print(np.linalg.matrix_rank(I))
print(np.linalg.det(I))
print(np.linalg.eig(I))

4
1.0
(array([1., 1., 1., 1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


Ранг единичной матрицы зависит от её размерности. Определитель единичной матрицы всегда равен 1. Собсвенные значения единицы.

In [24]:
A2 = np.random.rand(4, 4)
A2

array([[0.21275152, 0.52111589, 0.68852421, 0.02275196],
       [0.38684307, 0.8396129 , 0.36375464, 0.42165481],
       [0.06869324, 0.71560176, 0.67934018, 0.27631809],
       [0.24515015, 0.14575461, 0.92203048, 0.88678015]])

In [37]:
print(np.linalg.matrix_rank(A2))
print(np.linalg.det(A2))
print(np.linalg.eig(A2))

4
0.12639174482428067
(array([1.89551524+0.j        , 0.09622373+0.34121446j,
       0.09622373-0.34121446j, 0.53052207+0.j        ]), array([[-0.36671135+0.j        ,  0.67105751+0.j        ,
         0.67105751-0.j        , -0.56581482+0.j        ],
       [-0.53527214+0.j        , -0.33229393-0.06684002j,
        -0.33229393+0.06684002j, -0.2242965 +0.j        ],
       [-0.47138401+0.j        ,  0.14114956+0.39952796j,
         0.14114956-0.39952796j, -0.11730699+0.j        ],
       [-0.59733042+0.j        , -0.09749032-0.49572657j,
        -0.09749032+0.49572657j,  0.78471889+0.j        ]]))


In [25]:
DA = A2 * I
DA

array([[0.21275152, 0.        , 0.        , 0.        ],
       [0.        , 0.8396129 , 0.        , 0.        ],
       [0.        , 0.        , 0.67934018, 0.        ],
       [0.        , 0.        , 0.        , 0.88678015]])

In [38]:
print(np.linalg.matrix_rank(DA))
print(np.linalg.det(DA))
print(np.linalg.eig(DA))

4
0.10761059961204118
(array([0.21275152, 0.8396129 , 0.67934018, 0.88678015]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


Ранг диагональной матрицы зависти от её размерности(или числа элементов в её диагонали). Как и единичной матрицей это проистекает, что вектора n размерности, где координаты каждого вектора равны 0, кромей одной, и их индексы(местоположения) не совпадают. В этом случае они будут линейно независимы, а число линейно независимых векторов явялется рангом матрицы. Пример подобной линейной комбинации векторов - ортогональный базис для 3-х мерного пространства(i, j, k)

Собственные векторы диагональной матрице равны единичной матрице.

In [19]:
O = np.zeros([3, 3])
O

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
print(np.linalg.matrix_rank(O))
print(np.linalg.det(O))
print(np.linalg.eig(O))

0
0.0
(array([0., 0., 0.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


Ранг и определитель и собственные значения нулевой матрицы равны 0, а собственные векторы единичной матрице.